import type { Customer, CustomerEvent, CustomerRecipient, DeliveryTask, Invoice, Order, Payment, Product, ProductionTask, Staff, StoreData } from "../types";

const names = ["Nguyễn Minh Anh","Trần Hoàng Nam","Lê Thu Hà","Phạm Gia Hân","Đỗ Nhật Minh","Vũ Thanh Tú","Bùi Bảo Ngọc","Hoàng Đức Anh","Nguyễn Quỳnh Chi","Lâm Ngọc Mai","Công ty An Nhiên","Studio Nắng","Trương Quốc Bảo","Lý Phương Linh","Hồ Hải Yến","Đặng Khánh Vy","Mai Tuấn Kiệt","Phan Thảo My","Công ty Mây Việt","Ngô Minh Khang"];
const productSeed = [
  ["BH-001","Bó hồng Pastel","Hoa bó",850000,470000,"🌸"],["GH-002","Giỏ hoa Nắng Mai","Hoa giỏ",1250000,680000,"🌻"],["HH-003","Hộp hoa Mộng Mơ","Hoa hộp",980000,520000,"🌷"],["KT-004","Kệ hoa Khai Trương","Hoa sự kiện",2200000,1350000,"🌺"],["SN-005","Bó tulip Sinh Nhật","Hoa bó",1150000,650000,"💐"],["CB-006","Vòng hoa Chia Buồn","Hoa sự kiện",1800000,1100000,"🤍"],["HQ-007","Set hoa & Chocolate","Theo yêu cầu",1450000,820000,"🎁"],["CH-008","Bó cẩm chướng Dịu Dàng","Hoa bó",720000,390000,"🌷"],["CU-009","Hoa cưới Trắng Tinh","Theo yêu cầu",1600000,920000,"🤍"],["TC-010","Giỏ trái cây Premium","Giỏ quả",1350000,880000,"🍎"],["QT-011","Gấu bông Teddy","Theo yêu cầu",350000,190000,"🧸"],["TH-012","Thiệp viết tay","Theo yêu cầu",50000,12000,"💌"],["PK-013","Bóng bay trang trí","Theo yêu cầu",120000,45000,"🎈"],["HO-014","Bó hướng dương Rực Rỡ","Hoa bó",780000,420000,"🌻"],["LY-015","Bó lily Thanh Nhã","Hoa bó",1050000,580000,"🪷"],
] as const;
const sources = ["Facebook","Instagram","Zalo","Website","TikTok","Khách tại cửa hàng"];
const statuses = ["Mới","Đã xác nhận","Đang chuẩn bị","Chờ kiểm tra","Chờ giao","Đang giao","Đã hoàn thiện","Hoàn thành"];
const createdAt = "2026-08-15 08:00:00";

export function buildSeedStore(): StoreData {
  const staff:Staff[] = [
    {id:1,name:"Ngọc Lan",email:"lan@flore.vn",phone:"0909000101",role:"manager",avatar:"",active:true,createdAt},
    {id:2,name:"Nero Nguyễn",email:"nero@flore.vn",phone:"0909000102",role:"sales",avatar:"",active:true,createdAt},
    {id:3,name:"Mai Hoa",email:"hoa@flore.vn",phone:"0909000103",role:"florist",avatar:"",active:true,createdAt},
    {id:4,name:"Đức Long",email:"long@flore.vn",phone:"0909000104",role:"delivery",avatar:"",active:true,createdAt},
    {id:5,name:"Thảo Vy",email:"vy@flore.vn",phone:"0909000105",role:"accountant",avatar:"",active:true,createdAt},
  ];
  const products:Product[] = productSeed.map((p,index)=>({id:index+1,sku:p[0],name:p[1],category:p[2],price:p[3],cost:p[4],image:p[5],status:index===11?"hidden":index===8?"out_of_stock":"active",sold:8+(index*7)%42,revenue:(8+(index*7)%42)*p[3],createdAt}));
  const customers:Customer[] = names.map((name,index)=>({id:index+1,code:`CUS-${String(index+1).padStart(4,"0")}`,type:name.includes("Công ty")||name.includes("Studio")?"business":"individual",name,phone:`09${String(12000000+index*37691).slice(-8)}`,email:`khach${index+1}@example.com`,address:`${18+index} Đường Hoa Hồng, ${index%3===0?"Quận 1":index%3===1?"Quận 3":"Thủ Đức"}, TP.HCM`,source:sources[index%sources.length],company:name.includes("Công ty")||name.includes("Studio")?name:"",taxCode:"",segment:index<2?"VIP":index<7?"Thân thiết":index<14?"Quay lại":"Mới",tags:JSON.stringify(index<3?["Khách VIP","Hay mua > 1 triệu"]:[index%2?"Hoa sinh nhật":"Hoa kỷ niệm"]),notes:"",firstOrderAt:"2025-09-12",lastOrderAt:`2026-08-${String(2+(index%13)).padStart(2,"0")}`,totalOrders:index<2?12-index:1+(index%7),totalSpent:index<2?18450000-index*3200000:680000+index*375000,createdAt,staffName:index%2?"Nero Nguyễn":"Ngọc Lan"}));
  const recipients:CustomerRecipient[] = customers.map((customer,index)=>({id:index+1,customerId:customer.id,name:index%3===0?"Chị Thu":customer.name,phone:`09${String(45000000+index*18433).slice(-8)}`,address:`${42+index} ${index%2?"Nguyễn Huệ":"Lê Lợi"}, TP.HCM`,relationship:index%3===0?"Bạn bè":"Bản thân",birthday:index<8?`199${index%10}-${String(1+(index%12)).padStart(2,"0")}-${String(8+(index%18)).padStart(2,"0")}`:"",anniversary:"",notes:"",createdAt}));
  const events:CustomerEvent[] = recipients.slice(0,10).map((recipient,index)=>({id:index+1,customerId:recipient.customerId,recipientId:recipient.id,type:index%2?"Kỷ niệm":"Sinh nhật",title:`${index%2?"Kỷ niệm":"Sinh nhật"} ${recipient.name}`,eventDate:index%2?`2024-${String(9+(index%3)).padStart(2,"0")}-${String(10+index).padStart(2,"0")}`:recipient.birthday,remindDays:"[30,14,7,3,1]",notes:index%2?"Nhắc khách chọn hoa trước hai tuần":"",createdAt,customerName:customers[index].name,customerPhone:customers[index].phone,recipientName:recipient.name,relationship:recipient.relationship}));
  const orders:Order[]=[];const payments:Payment[]=[];const invoices:Invoice[]=[];const production:ProductionTask[]=[];const deliveries:DeliveryTask[]=[];const logs:StoreData["logs"]=[];
  for(let index=0;index<30;index+=1){
    const customer=customers[index%customers.length],product=products[(index*3)%products.length],quantity=index%7===0?2:1,subtotal=product.price*quantity,discount=index%6===0?100000:0,shipping=index%5===0?0:50000+(index%3)*15000,total=subtotal-discount+shipping,status=statuses[index%statuses.length];
    const paid=status==="Hoàn thành"?total:index%4===0?Math.round(total*.4):index%5===0?0:total,deliveryDay=String(15+(index%4)).padStart(2,"0"),deliveryTime=`${String(9+(index%10)).padStart(2,"0")}:${index%2?"30":"00"}`,orderId=index+1,recipient=recipients[index%recipients.length],orderCreated=`2026-08-${String(1+(index%15)).padStart(2,"0")} ${String(8+(index%9)).padStart(2,"0")}:30:00`;
    const order:Order={id:orderId,code:`FH-260815-${String(orderId).padStart(3,"0")}`,customerId:customer.id,customerName:customer.name,customerPhone:customer.phone,source:sources[index%sources.length],recipientName:recipient.name,recipientPhone:recipient.phone,deliveryAddress:recipient.address,mapsUrl:"https://maps.google.com",deliveryDate:`2026-08-${deliveryDay}`,deliveryTime,deliveryType:index%9===0?"pickup":"delivery",cardMessage:index%2?"Chúc em một ngày thật nhiều niềm vui và hạnh phúc!":"Happy birthday! Luôn rạng rỡ nhé.",notes:index%8===0?"Khách dặn giao nhẹ tay, gọi trước 10 phút.":"",status,paymentStatus:paid===0?"Chưa thanh toán":paid<total?"Đã cọc":"Đã thanh toán đủ",subtotal,discount,shippingFee:shipping,surcharge:0,total,paid,remaining:total-paid,dueDate:paid<total?"2026-08-20":"",createdAt:orderCreated,staffName:index%2?"Nero Nguyễn":"Ngọc Lan",itemProductId:product.id,itemName:product.name,itemSku:product.sku,quantity,unitPrice:product.price};orders.push(order);
    const delivered=["Đã hoàn thiện","Hoàn thành"].includes(status),deliveryStatus=delivered?"Đã giao":status==="Đang giao"?"Đang giao":"Chờ giao";
    deliveries.push({id:orderId,orderId,orderCode:order.code,recipientName:order.recipientName,recipientPhone:order.recipientPhone,deliveryAddress:order.deliveryAddress,mapsUrl:order.mapsUrl,deliveryDate:order.deliveryDate,deliveryTime:order.deliveryTime,status:deliveryStatus,cod:order.remaining,fee:shipping,notes:"Gọi người nhận trước khi đến",shipperId:4,shipperName:"Đức Long"});
    production.push({id:orderId,orderId,orderCode:order.code,customerName:order.customerName,deliveryDate:order.deliveryDate,deliveryTime:order.deliveryTime,cardMessage:order.cardMessage,status:delivered?"Đã hoàn thiện":["Chưa làm","Đang làm","Chờ kiểm tra"][index%3],dueAt:`${order.deliveryDate} ${deliveryTime}:00`,tone:["Pastel hồng","Trắng xanh","Vàng cam","Đỏ burgundy"][index%4],flowerTypes:["Hồng Ecuador","Tulip","Hướng dương","Cẩm chướng"][index%4],instructions:"Cắm thoáng, dáng tự nhiên, nơ lụa đồng màu",referenceImage:"",completedImage:"",floristId:3,floristName:"Mai Hoa",itemName:product.name});
    logs.push({id:orderId,orderId,action:"Tạo đơn",details:`${customer.name} đặt ${product.name}`,createdAt:orderCreated,staffName:"Nero Nguyễn"});
    if(paid>0)payments.push({id:payments.length+1,orderId,orderCode:order.code,customerName:customer.name,amount:paid,method:index%3===0?"Chuyển khoản":index%3===1?"QR":"Tiền mặt",reference:`PAY-${String(orderId).padStart(4,"0")}`,notes:index%4===0?"Tiền cọc":"Thanh toán đơn hàng",paidAt:orderCreated,staffName:"Nero Nguyễn"});
    if(index<10)invoices.push({id:index+1,number:`INV-2608-${String(index+1).padStart(4,"0")}`,orderId,orderCode:order.code,customerName:customer.name,total,status:"Đã phát hành",issuedAt:orderCreated,customerPhone:customer.phone,customerAddress:order.deliveryAddress,subtotal,discount,shippingFee:shipping,surcharge:0,paid,remaining:total-paid,paymentStatus:order.paymentStatus,itemName:product.name,quantity,unitPrice:product.price});
  }
  return {customers,recipients,events,products,orders,payments,invoices,staff,production,deliveries,logs,settings:{shop:{name:"Floré Flower Studio",address:"128 Nguyễn Huệ, Quận 1, TP.HCM",hotline:"0909 123 456",website:"flore.vn",facebook:"facebook.com/floreflower",bank:"Vietcombank · 0123456789 · NGUYEN NGOC LAN",footer:"Cảm ơn quý khách đã tin tưởng Floré!"},invoice:{showPhone:true,showAddress:true,showDiscount:true,showShipping:true,showQr:true},workflow:{productGroups:["Hoa bó","Hoa giỏ","Hoa hộp","Hoa bình","Giỏ quả","Giỏ quả & hoa","Hoa sự kiện","Theo yêu cầu"],defaultShippingFee:50000,defaultFloristId:3,defaultShipperId:4},notifications:{dueSoon:true,unpaid:true,specialOccasion:true}}};
}
